### ISSUE TITLE
problems in browsers

### ISSUE THREAD

**Issue by nchurch** [ckirkendall/The-Great-Todo#1]
In Firefox:

The form fields are too short for the text.

When todos are entered, nothing is visible in the 'add' field, but add successfully adds the text that was entered to the todo list.

Chrome:

The text is visible in the 'add' field, but most of the time the 'add' button yields a blank page, and the page must be reloaded to get anything to show.  (Sometimes, however, it does work.)

After reloading (and logging in again), one sees that the item was in fact successfully added to the to-do list, in spite of the blank page.

**Comment by nchurch** [comment]
The Firefox problem can be fixed by prepending <!DOCTYPE html> in all of the html files, to get the browser out of quirks mode.  This does not fix the problem in Chrome, however.

**Comment by nchurch** [comment]
Also, the request for deps.js is getting a 404 in both Firefox and Chrome, but since I don't know Closure or Clojurescript terribly well I'm not sure what this means.

**Comment by ckirkendall** [comment]
Thanks for debugging the firefox issues.  I will make the changes asap.  I discovered the issue with chrome actually during the presentation.  I am not sure what is going on.  It looks like list-html sometimes is return nil back from the template cache.  I am going to dig into that tonight to figure it out.

**Comment by ckirkendall** [comment]
I believe I fixed the issue.  I had a script tag in list.html that was causing chrome to get confused.  If you could bring down the changes and let me know if you still see the chrome issue.  I am going to leave this open for a little bit while I do some more testing.

**Comment by nchurch** [comment]
Chrome issue is fixed!  BTW, I'd be curious to know how you figured out/guessed that was the problem.

I found a separate issue though; making an issue for that.

**Comment by ckirkendall** [comment]
Fixed and verified
