### ISSUE TITLE
checking off items from todo list sometimes fails

### ISSUE THREAD

**Issue by nchurch** [ckirkendall/The-Great-Todo#2]
The trouble spots seem to be when the todo list gets reasonably big, and you are clicking on 'outside' checkboxes (either at the top or the bottom).

Also, logout doesn't work, but not sure if this was meant to be left unimplemented.

**Comment by ckirkendall** [comment]
I did intentionally not implement the login link. I wasn't going to cover it in my presentation.  It should just delete the security cookie and refresh the window.  I am having a hard time reproducing the issue with the checking off not working.  What browser/version do you see the issue in.

**Comment by nchurch** [comment]
It was in both Firefox and Chrome, but restarting mongod and creating a fresh account seems to get rid of it, so not sure what the problem really was.
